version: '3.9'
services:
  dapp:
    container_name: drapp
    image: fdrennan/rapp:main
    restart: 'no'
    user: 'root'
    ports:
    - '9000:8000'
    expose:
    - '9000'
    command: ["R", "-e", "shiny::runApp('/app/src')"]
    volumes:
      - .aws:/root/.aws # set up awscli and make sure path matches
      - .ssh:/root/.ssh # ssh keys created in the container will be deposited here
  cache:
    container_name: 'redis'
    restart: 'no'
    image: redis:6.2-alpine
    command: redis-server
    volumes:
      - ndexr_redis:/data
  sql:
    image: postgres:12.3
    container_name: ndexr_postgres
    restart: 'no'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    volumes:
      - ndexr_postgres:/var/lib/postgresql/data

volumes:
  ndexr_redis:
  ndexr_postgres:
